---
- name: Build services
  community.docker.docker_compose:
    project_src: /home/ubuntu/cloud-one/
    project_name: cloud-one
    build: yes
  register: compose_output

- debug:
    var: compose_output
