---
- name: "Scale services ({{ _scale }})"
  community.docker.docker_compose:
    project_src: "{{ _project_src }}"
    project_name: cloud-one
    state: present
    scale: "{{ _scale }}"
  register: compose_output

- debug:
    var: compose_output
