---
- name: "Stop services ({{ _services }})"
  community.docker.docker_compose:
    project_src: "{{ _project_src }}"
    project_name: cloud-one
    services: "{{ _services }}"
    state: present
    stopped: yes
  register: compose_output

- debug:
    var: compose_output
