---
- name: Up services
  community.docker.docker_compose:
    project_src: /home/ubuntu/cloud-one/
    project_name: cloud-one
    state: present
  register: compose_output

- debug:
    var: compose_output
