version: '3'


x-service-base: &service-base
  restart: unless-stopped
  networks: []
  volumes: []
  logging:
    driver: 'json-file'
    options:
      max-size: 10m
      max-file: '3'

x-bind-mount-base: &bind-mount-base
  driver: local
  driver_opts: &driver_opts
    type: none
    o: bind

x-env-DB: &env-DB
  DB_HOST: ${DB_HOST:-mariadb}
  DB_NAME: ${DB_NAME:-wordpress}
  DB_USER: ${DB_USER:-wordpress}
  DB_PASS: ${DB_PASS:-wordpress}

x-env-WP: &env-WP
  WP_URL: ${WP_URL:-localhost}
  WP_TITLE: ${WP_TITLE:-wordpress}
  WP_THEME: ${WP_THEME:-twentytwentyone}
  WP_ADMIN_MAIL: ${WP_ADMIN_MAIL:-admin@wordpress.com}
  WP_ADMIN_USER: ${WP_ADMIN_USER:-wordpress}
  WP_ADMIN_PASS: ${WP_ADMIN_PASS:-} # No default value because generated on first run if blank


services:
  mariadb:
    <<: *service-base
    build:
      context: images/mariadb
    image: mariadb
    networks:
      - mariadb
    volumes:
      - mariadb:/var/lib/mysql:rw
    environment:
      <<: *env-DB

  nginx:
    <<: *service-base
    build:
      context: images/nginx
    image: nginx
    networks:
      - nginx
    ports:
      - '443:443'
    volumes:
      - ./volumes/ssl/:/etc/nginx/ssl/:ro
      - ./volumes/wordpress/:/var/www/wordpress:ro
      - ./services/nginx/conf.tmpl.d/:/etc/nginx/conf.tmpl.d/:ro
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-login.42.fr}
      WP_HOST: ${WP_HOST:-wordpress}

  wordpress:
    <<: *service-base
    build:
      context: images/wordpress
    image: wordpress
    depends_on:
      - mariadb
    networks:
      - mariadb
      - nginx
    volumes:
      - ./volumes/wordpress/:/var/www/wordpress:rw
    environment:
      <<: *env-DB
      <<: *env-WP


networks:
  nginx:

  mariadb:


volumes:
  mariadb:

  wordpress-data:
   <<: *bind-mount-base
   driver_opts:
     <<: *driver_opts
     device: "/home/ubuntu/cloud-one/volumes/wordpress"
