- name: Install docker and docker-compose
  hosts: all
  gather_facts: false
  tags:
    - install
    - docker
  tasks:
    - name: Install dependencies
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip']
        state: present
        update_cache: yes

    - name: Add official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Enable docker at boot
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker SDK and docker-compose for python3
      pip:
        name: ['docker', 'docker-compose']


- name: Copy project files
  hosts: all
  gather_facts: false
  tags:
    - copy
  tasks:
    - name: Copy all files
      remote_user: ubuntu
      copy:
        src: ../../docker/
        dest: /home/ubuntu/cloud-one
        owner: ubuntu
        group: ubuntu
        mode: u=rw,g=r,o=r
