- name: Up services
  hosts: all
  gather_facts: false
  tags:
    - never
    - up
  tasks:
    - name: up
      community.docker.docker_compose:
        project_src: /home/ubuntu/cloud-one/
        project_name: cloud-one
        state: present
      register: compose_output

    - debug:
        var: compose_output


- name: Down services
  hosts: all
  gather_facts: false
  tags:
    - never
    - down
  tasks:
    - name: down
      community.docker.docker_compose:
        project_src: /home/ubuntu/cloud-one/
        project_name: cloud-one
        state: absent
      register: compose_output

    - debug:
        var: compose_output


- name: (Re)Start services
  hosts: all
  gather_facts: false
  tags:
    - never
    - start
    - restart
  tasks:
    - name: start
      community.docker.docker_compose:
        project_src: /home/ubuntu/cloud-one/
        project_name: cloud-one
        state: present
        restarted: yes
      register: compose_output

    - debug:
        var: compose_output


- name: Stop services
  hosts: all
  gather_facts: false
  tags:
    - never
    - stop
  tasks:
    - name: stop
      community.docker.docker_compose:
        project_src: /home/ubuntu/cloud-one/
        project_name: cloud-one
        state: present
        stopped: yes
      register: compose_output

    - debug:
        var: compose_output


