- name: Copy project files
  hosts: all
  gather_facts: false
  tags:
    - copy
  tasks:
    - name: Copy all files
      remote_user: ubuntu
      copy:
        src: ../../docker/
        dest: /home/ubuntu/cloud-one
        owner: ubuntu
        group: ubuntu
        mode: u=rwx,g=rx,o=rx

#   - name: chmod 600 SSL directory
#     remote_user: ubuntu
#     file:
#       path: /home/ubuntu/cloud-one/ssl/
#       mode: u=r,g=,o=


- name: Start services
  hosts: all
  gather_facts: false
  tags:
    - start
  tasks:
    - name: up
      community.docker.docker_compose:
        project_src: /home/ubuntu/cloud-one/
        project_name: cloud-one
      register: output

    - debug: var=output
